### ISSUE TITLE
work not fine in schinese

### ISSUE THREAD

**Issue by Mr54233** [niwith/DropInMultiplayer#6]
it can work ,
but some time it wouldnt read the command other (not host) text in the chatbox,
and look like the <welcome messnge> wouldnt work 
and it seems cant get the survivorlist so it cant list in the <join_as help>.
so we cant use the <join_as name> to join the game but we can join as some character like captian/commando/huntress/random even the railgunner (but it bug we cant use) ,the other character name cant be <Identify> by the mod
and very thank you to do this mod ,it takes me and my friends a lots of fun,
thank you

**Comment by Mr54233** [comment]
![image](https://user-images.githubusercontent.com/46802509/157253182-f08fb128-8890-46cb-8e8b-60abc7bf50f9.png)

**Comment by niwith** [comment]
This has been fixed in the latest patch
