### ISSUE TITLE
A problem about [Risk of Rain 2 Dedicated Server].

### ISSUE THREAD

**Issue by ZiYuanZiWan** [niwith/DropInMultiplayer#7]
When we use [Risk of Rain 2 Dedicated Server], after the player loses the connection, reconnects the game and uses the command [join_as MULT(or other roles)] in the chat box, the chat box will appear [Sorry!The host has made it so you can't use join as after selecting character.].Is this the wrong way we use it?

**Comment by ZiYuanZiWan** [comment]
I'm sorry, I see. I don't use it correctly. But since the game was updated, players who lost their connection can never be resurrected at the next level. Will always be a spectator mode. Can you solve this problem?

**Comment by MrTinTin9527** [comment]
i have same problem, how to solve it?

**Comment by ZiYuanZiWan** [comment]
> i have same problem, how to solve it?

Although the last update has solved the problem that you can't continue to play after losing your connection, you still can't play with more than four people, even if the config has been modified.

**Comment by MrTinTin9527** [comment]
I mean,when i try to join, i also received [Sorry!The host has made it so you can't use join as after selecting character.] Should I try other instructions?

**Comment by ZiYuanZiWan** [comment]
> I mean,when i try to join, i also received [Sorry!The host has made it so you can't use join as after selecting character.] Should I try other instructions?

I think the main function of this mod is to join the game in the middle of the game when you don't choose a character before the game starts. You can see [Sorry!The host has made it so you can't use join as after selecting character.]is: you chose a character before the game started. If you can't resurrection, please try to update [Risk of Rain 2 Dedicated Server].

**Comment by MrTinTin9527** [comment]
> > 我的意思是，当我尝试加入时，我也收到了[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。我应该尝试其他说明吗？
> 
> 我认为这个mod的主要功能是在游戏开始前不选择角色时，在游戏中间加入游戏。你可以看到[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。是：你在游戏开始前选择了一个角色。如果您无法复活，请尝试更新[下雨的风险2专用服务器]。

I understand, thank you

**Comment by ZiYuanZiWan** [comment]
> > > 我的意思是，当我尝试加入时，我也收到了[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。我应该尝试其他说明吗？
> > 
> > 
> > 我认为这个mod的主要功能是在游戏开始前不选择角色时，在游戏中间加入游戏。你可以看到[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。是：你在游戏开始前选择了一个角色。如果您无法复活，请尝试更新[下雨的风险2专用服务器]。
> 
> I understand, thank you

我就说怎么看起来怪怪的，原来不是歪果仁，我的建议是等更新，然后我们一起玩Minecraft，还有你的网页翻译好逊啊（）。

**Comment by MrTinTin9527** [comment]
> > > > 我的意思是，当我尝试加入时，我也收到了[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。我应该尝试其他说明吗？
> > > 
> > > 
> > > 我认为这个mod的主要功能是在游戏开始前不选择角色时，在游戏中间加入游戏。你可以看到[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。是：你在游戏开始前选择了一个角色。如果您无法复活，请尝试更新[下雨的风险2专用服务器]。
> > 
> > 
> > 我明白了，谢谢
> 
> 我就说怎么看起来怪怪的，原来不是歪果仁，我的建议是等更新，然后我们一起玩Minecraft，还有你的网页翻译好逊啊（）。

哈哈哈，我英语不得行，纯机翻。mc我和朋友们断断续续玩，隔几个月见到好玩的模组就去玩一阵子，然后扔下...如此循环

**Comment by ZiYuanZiWan** [comment]
> > > > > 我的意思是，当我尝试加入时，我也收到了[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。我应该尝试其他说明吗？
> > > > 
> > > > 
> > > > 我认为这个mod的主要功能是在游戏开始前不选择角色时，在游戏中间加入游戏。你可以看到[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。是：你在游戏开始前选择了一个角色。如果您无法复活，请尝试更新[下雨的风险2专用服务器]。
> > > 
> > > 
> > > 我明白了，谢谢
> > 
> > 
> > 我就说怎么看起来怪怪的，原来不是歪果仁，我的建议是等更新，然后我们一起玩Minecraft，还有你的网页翻译好逊啊（）。
> 
> 哈哈哈，我英语不得行，纯机翻。mc我和朋友们断断续续玩，隔几个月见到好玩的模组就去玩一阵子，然后扔下...如此循环

我正好也在开一个服务器，如果有兴趣，可以加一下：1033103813。

**Comment by MrTinTin9527** [comment]
> > > > > > 我的意思是，当我尝试加入时，我也收到了[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。我应该尝试其他说明吗？
> > > > > 
> > > > > 
> > > > > 我认为这个mod的主要功能是在游戏开始前不选择角色时，在游戏中间加入游戏。你可以看到[对不起！主持人已经这样做了，所以你不能在选择字符后使用加入。是：你在游戏开始前选择了一个角色。如果您无法复活，请尝试更新[下雨的风险2专用服务器]。
> > > > 
> > > > 
> > > > 我明白了，谢谢
> > > 
> > > 
> > > 我就说怎么看起来怪怪的，原来不是歪果仁，我的建议是等更新，然后我们一起玩Minecraft，还有你的网页翻译好逊啊（）。
> > 
> > 
> > 哈哈哈，我英语不得行，纯机翻。mc我和朋友们断断续续玩，隔几个月见到好玩的模组就去玩一阵子，然后扔下...如此循环
> 
> 我正好也在开一个服务器，如果有兴趣，可以加一下：1033103813。

刚刚申请了

**Comment by niwith** [comment]
This issue should be fixed in the latest patch.
Thanks for reporting the issue :)
